#define PIKA_OPTIMIZE PIKA_OPTIMIZE_SPEED
// #define PIKA_DEBUG_ENABLE 1
// #define PIKA_FREERTOS_ENABLE 1
// #define PIKA_DEBUG_ENABLE    1
// #define PIKA_THREAD_STACK_SIZE 1024 * 32
// #define PIKA_EVENT_THREAD_STACK_SIZE 1024 * 40
