
class BLE:
    def init(self) -> int: ...
    
    def pyi_test(self) -> int: ...
    
    def test2(self) -> int: ...
    
    def pyi_check_active(self) -> bool: ...

    def pyi_active(self,active : bool) -> bool: ...
    
    def stop_advertise(self) -> int: ...
    
    def set_adv_data(self, data:str, data_len: int ) -> int : ...

    def set_rsp_data(self, data:str, data_len: int ) -> int : ...

    def gap_connect(self, addr_type : int, addr : str ,scan_duration_ms : int) -> int : ...

    def gap_disconnect(self) -> int : ...

    def advertise(self,own_addr_type : int, interval_us : int, connectable : bool ) -> int: ... 

    def gap_stop_scan() -> int: ...
    
    def gatts_register_svcs(services_info : tuple) -> int: ...

    def gap_scan(self, addr_mode : int, duration_ms:int, interval_us:int, window_us:int, active:bool) -> int: ...

    def setCallback(self, cb: any): ...

    # FIXME:mac地址的返回值,应类似于b'4\x85\x18\x90\x87.'
    def config_mac_get(self) -> int: ...

    def config_addr_mode_get(self) -> int :...

    # FIXME:gap_name的返回值应该是字符串" "
    def config_gap_name_get(self) -> str :...
    
    def config_mtu_get(self) -> int:...

    def config_addr_rxbuf_get(self) -> int:...

    def config_bond_get(self) -> int:...

    def config_mitm_get(self) -> int:...
    
    def config_io_get(self) -> int:...
    
    def config_le_secure_get(self) -> int:...

    def config_mac_update(mac) -> int:...
        
    def config_addr_mode_update(addr_mode) -> int:...

    def config_gap_name_update(gap_name : str) -> int: ...

    def config_rxbuf_update(rxbuf : int) -> int:...

    def config_mtu_update(mtu : int) -> int:...
        
    def config_bond_update(bond : bool ) -> int:...

    def config_mitm_update(mitm : bool ) -> int:...

    def config_io_update(io : int ) -> int:...

    def config_le_secure_update(le_secure : bool ) -> int:...




