_IRQ_CENTRAL_CONNECT               = 1
_IRQ_CENTRAL_DISCONNECT            = 2
_IRQ_GATTS_WRITE                   = 3
_IRQ_GATTS_READ_REQUEST            = 4
_IRQ_SCAN_RESULT                   = 5
_IRQ_SCAN_DONE                     = 6
_IRQ_PERIPHERAL_CONNECT            = 7
_IRQ_PERIPHERAL_DISCONNECT         = 8
_IRQ_GATTC_SERVICE_RESULT          = 9
_IRQ_GATTC_SERVICE_DONE            = 10
_IRQ_GATTC_CHARACTERISTIC_RESULT   = 11
_IRQ_GATTC_CHARACTERISTIC_DONE     = 12
_IRQ_GATTC_DESCRIPTOR_RESULT       = 13
_IRQ_GATTC_DESCRIPTOR_DONE         = 14
_IRQ_GATTC_READ_RESULT             = 15
_IRQ_GATTC_READ_DONE               = 16
_IRQ_GATTC_WRITE_DONE              = 17
_IRQ_GATTC_NOTIFY                  = 18
_IRQ_GATTC_INDICATE                = 19
_IRQ_GATTS_INDICATE_DONE           = 20
_IRQ_MTU_EXCHANGED                 = 21
_IRQ_L2CAP_ACCEPT                  = 22
_IRQ_L2CAP_CONNECT                 = 23
_IRQ_L2CAP_DISCONNECT              = 24
_IRQ_L2CAP_RECV                    = 25
_IRQ_L2CAP_SEND_READY              = 26
_IRQ_CONNECTION_UPDATE             = 27
_IRQ_ENCRYPTION_UPDATE             = 28
_IRQ_GET_SECRET                    = 29
_IRQ_SET_SECRET                    = 30
_IRQ_GATTC_SUBSCRIBE               = 31   #往后事件均相较mpy新增
_IRQ_GATTS_SUBSCRIBE               = 32
_IRQ_TEST                          = 33

#客户端读请求返回值
_GATTS_NO_ERROR                          =  0x00
_GATTS_ERROR_READ_NOT_PERMITTED          =  0x02
_GATTS_ERROR_WRITE_NOT_PERMITTED         =  0x03
_GATTS_ERROR_INSUFFICIENT_AUTHENTICATION =  0x05
_GATTS_ERROR_INSUFFICIENT_AUTHORIZATION  =  0x08
_GATTS_ERROR_INSUFFICIENT_ENCRYPTION     =  0x0f

