/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#include "PikaMain.h"
#include <stdio.h>
#include <stdlib.h>

volatile PikaObj *__pikaMain;
PikaObj *pikaPythonInit(void){
    pika_platform_printf("======[pikapython packages installed]======\r\n");
    pika_printVersion();
    pika_platform_printf("ESP32==v0.4.2\r\n");
    pika_platform_printf("PikaStdDevice==v2.4.0\r\n");
    pika_platform_printf("PikaStdLib==v1.12.5\r\n");
    pika_platform_printf("network==v0.1.3\r\n");
    pika_platform_printf("pika_libc==v1.0.2\r\n");
    pika_platform_printf("time==v0.1.9\r\n");
    pika_platform_printf("===========================================\r\n");
    PikaObj* pikaMain = newRootObj("pikaMain", New_PikaMain);
    __pikaMain = pikaMain;
    extern unsigned char pikaModules_py_a[];
    obj_linkLibrary(pikaMain, pikaModules_py_a);
#if PIKA_INIT_STRING_ENABLE
    obj_run(pikaMain,
            "import PikaStdLib\n"
            "import machine \n"
            "import bluetooth\n"
            "import mytest\n"
            "print('hello PikaPython')\n"
            "a = bluetooth.BLE()\n"
            "a.active()\n"
            "# mem = PikaStdLib.MemChecker()\n"
            "# print('mem used max:')\n"
            "# mem.max()\n"
            "# print('mem used now:')\n"
            "# mem.now()\n"
            "\n");
#else 
    obj_runModule((PikaObj*)pikaMain, "main");
#endif
    return pikaMain;
}

